
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andregeraldes
 */
public class Game extends javax.swing.JFrame {
    public static String online;
    public static int uscore;
    public static int label;
    /**
     * Creates new form Game
     */
    public Game() {
        this.online = "";
        this.label = 1;
        initComponents();
        this.bemvindo.setText("Bem-vindo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bemvindo = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jogo = new javax.swing.JMenu();
        Criar_Desafio = new javax.swing.JMenuItem();
        listard = new javax.swing.JMenuItem();
        def = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(753, 489));
        jPanel1.setSize(new java.awt.Dimension(753, 489));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        bemvindo.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        bemvindo.setText("jLabel1");

        resultado.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(bemvindo))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(bemvindo))
        );

        inicio.setText("Inicio");

        jMenuItem2.setText("Login");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        inicio.add(jMenuItem2);

        jMenuItem1.setText("Registar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        inicio.add(jMenuItem1);

        jMenuBar1.add(inicio);

        jogo.setText("Jogo");
        jogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogoMouseClicked(evt);
            }
        });

        Criar_Desafio.setText("Criar");
        Criar_Desafio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Criar_DesafioMouseClicked(evt);
            }
        });
        Criar_Desafio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criar_DesafioActionPerformed(evt);
            }
        });
        jogo.add(Criar_Desafio);

        listard.setText("Listar");
        listard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listardMouseClicked(evt);
            }
        });
        listard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listardActionPerformed(evt);
            }
        });
        jogo.add(listard);

        jMenuBar1.add(jogo);

        def.setText("Definições");
        jMenuBar1.add(def);

        jMenu3.setText("Logout");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(online.equals("")){
            new MenuRegistar().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        // TODO add your handling code here:
        if(online.equals("")){
            new MenuLogin().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        if(!this.online.equals("")){
        try (
            // Criar datagrama socket
            DatagramSocket socket = new DatagramSocket()) {
            byte[] buf = new byte[256];
            byte[] rec = new byte[256];
            InetAddress address = InetAddress.getLocalHost();
            
            // PDU de LOGOUT
            String pedido = "PDU[ver=0,seg=0,label=" + label++ + ",tipo=LOGOUT]"; 
            
            buf = pedido.getBytes();
            DatagramPacket packet = new DatagramPacket(buf, buf.length, address, 4445);
            socket.send(packet);
                    
            // Receber resposta
            packet = new DatagramPacket(rec, rec.length);
            socket.receive(packet);
            
            // Apresentar resposta
            String received = new String(packet.getData(), 0, packet.getLength());
            
            String[] r;
            r = received.split(":\\[");
            r = r[1].split(("="));
            String tipo = r[0];
            if(tipo.equals("00")){               
                JOptionPane.showMessageDialog(null, "Logout efectuado com sucesso");            
            }
            else {
                JOptionPane.showMessageDialog(null, "Utilizador não logado");
            }
        } catch (SocketException ex) {
            Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.online = "";
        this.uscore = 0;
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jogoMouseClicked

    private void Criar_DesafioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criar_DesafioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Criar_DesafioActionPerformed

    private void Criar_DesafioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Criar_DesafioMouseClicked
        // TODO add your handling code here:
        if(!online.equals("")){
            
        }
    }//GEN-LAST:event_Criar_DesafioMouseClicked

    private void listardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listardActionPerformed

    private void listardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listardMouseClicked
        // TODO add your handling code here:
        if(!online.equals("")){
            
        }
    }//GEN-LAST:event_listardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Criar_Desafio;
    private javax.swing.JLabel bemvindo;
    private javax.swing.JMenu def;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jogo;
    private javax.swing.JMenuItem listard;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
