
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andregeraldes
 */
public class MenuCriarDesafio extends javax.swing.JFrame {
    private int hc = 0;
    /**
     * Creates new form MenuCriarDesafio
     */
    public MenuCriarDesafio() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeDesafio = new javax.swing.JTextField();
        horas = new javax.swing.JSpinner(new SpinnerDateModel());
        jLabel2 = new javax.swing.JLabel();
        criarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jPanel1.setSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do desafio:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 100, 138, 20);
        jPanel1.add(nomeDesafio);
        nomeDesafio.setBounds(170, 100, 171, 28);

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(horas, "HH:mm:ss dd-MM-yyyy");
        horas.setEditor(timeEditor);
        horas.setValue(new Date());
        horas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                horasStateChanged(evt);
            }
        });
        horas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                horasMouseClicked(evt);
            }
        });
        jPanel1.add(horas);
        horas.setBounds(170, 130, 171, 28);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data do desafio:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 130, 128, 20);

        criarButton.setText("Criar desafio");
        criarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarButtonMouseClicked(evt);
            }
        });
        jPanel1.add(criarButton);
        criarButton.setBounds(170, 170, 171, 29);

        jButton2.setText("Voltar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 200, 171, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pulse.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void criarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarButtonMouseClicked
        // TODO add your handling code here:
        boolean desafio = false;
        Date h = (Date) horas.getValue();
     
        String pedido = "";
        
        if(!nomeDesafio.getText().equals("") ){
            if(hc == 1){
                // Data actual
                Date n = new Date();
                Date max = new Date();
                max.setDate(31);
                max.setMonth(11);
                max.setYear(199);

                if(h.after(n) && h.before(max)){
                    pedido = "PDU[ver=0,seg=0,label=" + Game.label++ + ",tipo=MAKE_CHALLENGE]Lista de Campos:[07=\""+ nomeDesafio.getText() +"\",04="+String.format("%02d", h.getYear()-100) + String.format("%02d", h.getMonth()+1) + String.format("%02d", h.getDate()) +",05="+ String.format("%02d", h.getHours()) + String.format("%02d", h.getMinutes()) + String.format("%02d", h.getSeconds())+"]";                                           
                    desafio = true;
                }
                else JOptionPane.showMessageDialog(null, "Data inválida");
            }
            else {
                pedido = "PDU[ver=0,seg=0,label=" + Game.label++ + ",tipo=MAKE_CHALLENGE]Lista de Campos:[07=\""+ nomeDesafio.getText() +"\"]";
                desafio = true;
            }       
        } 
        else JOptionPane.showMessageDialog(null, "Nome inválido");
        
        if(desafio){
            //Enviar pedido 
            try (DatagramSocket socket = new DatagramSocket()) {
                byte[] buf = new byte[256];
                byte[] rec = new byte[256];
                InetAddress address = InetAddress.getLocalHost();
   
                buf = pedido.getBytes();
                DatagramPacket packet = new DatagramPacket(buf, buf.length, address, 4445);
                socket.send(packet);

                // Receber resposta
                packet = new DatagramPacket(rec, rec.length);
                socket.receive(packet);

                // Apresentar resposta
                String received = new String(packet.getData(), 0, packet.getLength());

                String[] r;
                r = received.split(":\\[");
                r = r[1].split(("="));
                String tipo = r[0];
                if(tipo.equals("00")){               
                    JOptionPane.showMessageDialog(null, "Desafio criado"); 
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Desafio não criado");
                }
            } catch (SocketException ex) {
                Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnknownHostException ex) {
                Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MenuLogin.class.getName()).log(Level.SEVERE, null, ex);
            }                    
        }      
    }//GEN-LAST:event_criarButtonMouseClicked

    private void horasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horasMouseClicked
        // TODO add your handling code here:
        hc = 1;
    }//GEN-LAST:event_horasMouseClicked

    private void horasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_horasStateChanged
        // TODO add your handling code here:
        hc = 1;
    }//GEN-LAST:event_horasStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCriarDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCriarDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCriarDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCriarDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCriarDesafio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarButton;
    private javax.swing.JSpinner horas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeDesafio;
    // End of variables declaration//GEN-END:variables
}
